//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34014
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace virtualClothing.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("virtualClothing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Type {0} does not support event: {1}.
        /// </summary>
        internal static string CommandOnEventException {
            get {
                return ResourceManager.GetString("CommandOnEventException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connect a device first!.
        /// </summary>
        internal static string ConnectDeviceFirst {
            get {
                return ResourceManager.GetString("ConnectDeviceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To get started.
        /// </summary>
        internal static string EngagementHandoffGetStarted {
            get {
                return ResourceManager.GetString("EngagementHandoffGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lift your hand.
        /// </summary>
        internal static string EngagementHandoffKeepControl {
            get {
                return ResourceManager.GetString("EngagementHandoffKeepControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selected experience is invalid.
        /// </summary>
        internal static string HomeScreenInvalidExperienceSelected {
            get {
                return ResourceManager.GetString("HomeScreenInvalidExperienceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The supplied Uri {0} points to an invalid article model.
        /// </summary>
        internal static string InvalidArticle {
            get {
                return ResourceManager.GetString("InvalidArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The supplied Uri {0} points to a invalid content.
        /// </summary>
        internal static string InvalidPanningContent {
            get {
                return ResourceManager.GetString("InvalidPanningContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Kinect Controller is invalid.
        /// </summary>
        internal static string KinectControllerInvalid {
            get {
                return ResourceManager.GetString("KinectControllerInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No ready kinect found.
        /// </summary>
        internal static string NoKinectReady {
            get {
                return ResourceManager.GetString("NoKinectReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to write screenshot to.
        /// </summary>
        internal static string ScreenshotWriteFailed {
            get {
                return ResourceManager.GetString("ScreenshotWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Screenshot saved to.
        /// </summary>
        internal static string ScreenshotWriteSuccess {
            get {
                return ResourceManager.GetString("ScreenshotWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You have selected {0}.
        /// </summary>
        internal static string ScrollingListSelectionMessage {
            get {
                return ResourceManager.GetString("ScrollingListSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You selected item #{0}.
        /// </summary>
        internal static string SelectedMessage {
            get {
                return ResourceManager.GetString("SelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lift your hand.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a to keep control.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Running it in a lower resolution may result in incorrect layout and reduced functionality..
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you wish to continue?.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This sample was designed 1920 x 1080 screen resolution..
        /// </summary>
        internal static string SuboptimalScreenResolutionMessage {
            get {
                return ResourceManager.GetString("SuboptimalScreenResolutionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Suboptimal Screen Resolution.
        /// </summary>
        internal static string SuboptimalScreenResolutionTitle {
            get {
                return ResourceManager.GetString("SuboptimalScreenResolutionTitle", resourceCulture);
            }
        }
    }
}
